# Generated by Django 5.1 on 2024-09-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=500)),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
