# Generated by Django 5.1 on 2024-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_chat_message_chat'),
        ('users', '0004_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='direct_messages.chat'),
        ),
    ]
