# Generated by Django 5.1 on 2024-09-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_chat_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
