# Generated by Django 5.1 on 2024-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
